name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: $GCLOUD_SERVICE_KEY

      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: $GOOGLE_PROJECT_ID

      - uses: actions/checkout@v4

      - run: |
          cd go.opentelemetry.io
          chmod 755 deploy.sh
          ./deploy.sh
